name: Microservice CI/CD

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v5
      with:
        context: ./user-service
        file: ./user-service/Dockerfile
        push: true
        tags: ${{ secrets.REGISTRY_USERNAME }}/user-service:latest

    - name: Update Kubernetes Manifest with new Image Tag 
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"

        sed -i 's|image: .*/user-service:.*|image: ${{ secrets.REGISTRY_USERNAME }}/user-service:${{ github.sha }}|g' k8s/deployment.yaml

        git add user-service/k8s/deployment.yaml
        git commit -m "ci: update image tag to ${{ github.sha }}"
        git push origin main
      